export enum warnMessages{
    mobileError = 'MOBILE NUMBER IS NOT VALID',
    dobError = 'DATE OF BIRTH REQUIRED',
    fnameError = 'FIRST  NAME  REQUIRED',
    lnameError = 'LAST NAME REQUIRED',
    addressError = 'NIC NUMBER REQUIRED',
    nicError = 'NIC NUMBER REQUIRED',
    nicError2 = 'PLEASE ENTER VALID NIC',
    mobileErrorMin = 'MOBILE NUMBER MUST BE 9 CHARACTERS LONG',
    requiredmobileError = 'MOBILE NUMBER REQUIRED',
    emailError1 = 'EMAIL ADDRESS REQUIRED',
    emailError2 = 'EMAIL ADDRESS SHOULD BE VALID',
    startDateError = 'START DATE REQUIRED',
    startMinDateError = 'START DATE SHOULD BE GREATER THAN 2020-01-01',
    startMaxDateError = 'START DATE SHOULD BE LESS THAN CURRENT DATE',
    endDateError = 'END DATE REQUIRED',
}